
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innovation4Austria.logic
{

using System;
    using System.Collections.Generic;
    
public partial class alleRechnungenAllerFirmen
{

    public int Firmen_id { get; set; }

    public Nullable<bool> Aktiv { get; set; }

    public System.DateTime Buchungsdetaildatum { get; set; }

    public decimal Preis { get; set; }

    public int Rechnungsdetail_id { get; set; }

    public Nullable<System.DateTime> datum { get; set; }

    public int Rechnung_id { get; set; }

}

}
