
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innovation4Austria.logic
{

using System;
    using System.Collections.Generic;
    
public partial class AlleRechnungenEinerFirma
{

    public Nullable<System.DateTime> RechnungsAussstellungsDatum { get; set; }

    public int Rechnungs_id { get; set; }

    public int Rechnungsdetails_id { get; set; }

    public int Buchungsdetails_id { get; set; }

    public System.DateTime BuchungsDetailDatum { get; set; }

    public decimal BuchungsDetailPreis { get; set; }

    public int Buchungs_id { get; set; }

    public bool BuchungAktiv { get; set; }

    public int raum_id { get; set; }

    public string Raumbezeichnung { get; set; }

    public string Raumartbezeichnung { get; set; }

}

}
