
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innovation4Austria.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Ausstattung
{

    public Ausstattung()
    {

        this.AlleRaum_Ausstattungen = new HashSet<Raum_Ausstattung>();

    }


    public int Id { get; set; }

    public string Bezeichnung { get; set; }

    public bool aktiv { get; set; }



    public virtual ICollection<Raum_Ausstattung> AlleRaum_Ausstattungen { get; set; }

}

}
