
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innovation4Austria.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Benutzer
{

    public Benutzer()
    {

        this.AlleLog = new HashSet<Log>();

    }


    public int Id { get; set; }

    public byte[] Passwort { get; set; }

    public string Emailadresse { get; set; }

    public string Vorname { get; set; }

    public string Nachname { get; set; }

    public Nullable<int> Firma_id { get; set; }

    public int Rolle_id { get; set; }

    public bool Aktiv { get; set; }



    public virtual Firma Firma { get; set; }

    public virtual Rolle Rolle { get; set; }

    public virtual ICollection<Log> AlleLog { get; set; }

}

}
