
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innovation4Austria.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Buchung
{

    public Buchung()
    {

        this.AlleBuchungsdetails = new HashSet<Buchungsdetails>();

    }


    public int Id { get; set; }

    public int Raum_id { get; set; }

    public int Firma_id { get; set; }

    public Nullable<bool> Aktiv { get; set; }



    public virtual Firma Firma { get; set; }

    public virtual Raum Raum { get; set; }

    public virtual ICollection<Buchungsdetails> AlleBuchungsdetails { get; set; }

}

}
