
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Innovation4Austria.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Buchungsdetails
{

    public Buchungsdetails()
    {

        this.Rechnungsdetails = new HashSet<Rechnungsdetails>();

    }


    public int Id { get; set; }

    public int Buchung_id { get; set; }

    public decimal Preis { get; set; }

    public System.DateTime Datum { get; set; }



    public virtual Buchung Buchung { get; set; }

    public virtual ICollection<Rechnungsdetails> Rechnungsdetails { get; set; }

}

}
