//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovation4Austria.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raum
    {
        public Raum()
        {
            this.AlleBilder = new HashSet<Bild>();
            this.AlleBuchungen = new HashSet<Buchung>();
            this.AlleRaum_Ausstattungen = new HashSet<Raum_Ausstattung>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Beschreibung { get; set; }
        public int Bauwerk_id { get; set; }
        public int Groesse { get; set; }
        public int Art_id { get; set; }
        public int Preis { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    
        public virtual Art Art { get; set; }
        public virtual Bauwerk Bauwerk { get; set; }
        public virtual ICollection<Bild> AlleBilder { get; set; }
        public virtual ICollection<Buchung> AlleBuchungen { get; set; }
        public virtual ICollection<Raum_Ausstattung> AlleRaum_Ausstattungen { get; set; }
    }
}
