//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovation4Austria.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnung
    {
        public Rechnung()
        {
            this.AlleRechnungsdetails = new HashSet<Rechnungsdetails>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual ICollection<Rechnungsdetails> AlleRechnungsdetails { get; set; }
    }
}
