//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatenManipulation.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tisch
    {
        public int ID { get; set; }
        public int PersonenAnzahl { get; set; }
        public int Raum_ID { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual Raum Raum { get; set; }
    }
}
