//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innovation4Austria.web {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validierungen {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validierungen() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Innovation4Austria.web.Validierungen", typeof(Validierungen).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profil wurde erfolgreich aktualisiert ähnelt.
        /// </summary>
        internal static string BenutzerProfilAktualisierenErfolgreich {
            get {
                return ResourceManager.GetString("BenutzerProfilAktualisierenErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bezahlung hat nicht geklappt ähnelt.
        /// </summary>
        internal static string BezahlungNichtMoeglich {
            get {
                return ResourceManager.GetString("BezahlungNichtMoeglich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchung erfolgreich erstellt ähnelt.
        /// </summary>
        internal static string BuchenErfolgreich {
            get {
                return ResourceManager.GetString("BuchenErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchung fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string BuchenFehlgeschlagen {
            get {
                return ResourceManager.GetString("BuchenFehlgeschlagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Emailadress  ähnelt.
        /// </summary>
        internal static string DataTypeMail {
            get {
                return ResourceManager.GetString("DataTypeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firma anlegen erfolgreich ähnelt.
        /// </summary>
        internal static string FirmaAnlegegSuccess {
            get {
                return ResourceManager.GetString("FirmaAnlegegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firma anlegen fehlgeschlagen ähnelt.
        /// </summary>
        internal static string FirmaAnlegenError {
            get {
                return ResourceManager.GetString("FirmaAnlegenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben innerhalb von 3 Tagen storniert ähnelt.
        /// </summary>
        internal static string InnerhalbVon3TagenStroniert {
            get {
                return ResourceManager.GetString("InnerhalbVon3TagenStroniert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buchstaben von A - Z ähnelt.
        /// </summary>
        internal static string NamensKontrolle {
            get {
                return ResourceManager.GetString("NamensKontrolle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort stimmt nicht überein ähnelt.
        /// </summary>
        internal static string NeuesPasswort {
            get {
                return ResourceManager.GetString("NeuesPasswort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password, min 5 Zeichen ähnelt.
        /// </summary>
        internal static string Passwort {
            get {
                return ResourceManager.GetString("Passwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort erfolgreich gewechselt ähnelt.
        /// </summary>
        internal static string Passwortgewechselt {
            get {
                return ResourceManager.GetString("Passwortgewechselt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwortwechsel fehlgeschlagen ähnelt.
        /// </summary>
        internal static string PasswortwechselError {
            get {
                return ResourceManager.GetString("PasswortwechselError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die max 5 Stellen ähnelt.
        /// </summary>
        internal static string Postleitzahl {
            get {
                return ResourceManager.GetString("Postleitzahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld ähnelt.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen bei Innovation 4 Autria ähnelt.
        /// </summary>
        internal static string SpeichernErfolgreich {
            get {
                return ResourceManager.GetString("SpeichernErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string SpeichernFehlgeschlagen {
            get {
                return ResourceManager.GetString("SpeichernFehlgeschlagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stronierung war erfolgreich ähnelt.
        /// </summary>
        internal static string StornoErfolreich {
            get {
                return ResourceManager.GetString("StornoErfolreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum 8 Zeichen und max. 16 Zeichen ähnelt.
        /// </summary>
        internal static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen fehlgeschlagen! ähnelt.
        /// </summary>
        internal static string SuchenFehlgeschlagen {
            get {
                return ResourceManager.GetString("SuchenFehlgeschlagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ungültiges Datum ähnelt.
        /// </summary>
        internal static string UngueltigesDatum {
            get {
                return ResourceManager.GetString("UngueltigesDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wurde schon bezahlt ähnelt.
        /// </summary>
        internal static string WurdeSchonBezahlt {
            get {
                return ResourceManager.GetString("WurdeSchonBezahlt", resourceCulture);
            }
        }
    }
}
