//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bauwerk
    {
        public int id { get; set; }
        public string strasse { get; set; }
        public int nummer { get; set; }
        public int plz { get; set; }
        public string ort { get; set; }
        public string bezeichnung { get; set; }
        public Nullable<bool> aktiv { get; set; }
    }
}
